project_id = "rzmcoxnfcpqqyxgkafwk"

[functions.copilot]
verify_jwt = false

[functions.connect-google]
verify_jwt = false

[functions.mcp-connect]
verify_jwt = false

[functions.migrate-helper]
verify_jwt = false
