"""
Baut public/docs grants.json und src/data/grants.generated.ts aus dem neuesten
normalisierten Foerderprogramm-Datensatz.
"""
import json
import shutil
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
GRANTS_DIR = ROOT / "data" / "grants"
PUBLIC_DIR = ROOT / "public"
DOCS_DIR = ROOT / "docs"
SRC_DATA_DIR = ROOT / "src" / "data"


def ts_string(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def run() -> None:
    files = sorted(GRANTS_DIR.glob("grants_*.json"))
    if not files:
        raise SystemExit("Keine grants_*.json gefunden. normalize_grants.py zuerst ausführen.")

    latest = files[-1]
    data = json.loads(latest.read_text(encoding="utf-8"))
    grants = data.get("grants", [])

    stats = {
        "total_grants": len(grants),
        "regions": sorted({g.get("region", "Deutschland") for g in grants}),
        "categories": sorted({g.get("category", "foerderung") for g in grants}),
        "last_updated": datetime.now(UTC).strftime("%Y-%m-%d"),
    }
    output = {
        "generated_at": datetime.now(UTC).isoformat(),
        "source_file": latest.name,
        "stats": stats,
        "grants": grants,
    }

    out_path = PUBLIC_DIR / "grants.json"
    out_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    if DOCS_DIR.exists():
        shutil.copyfile(out_path, DOCS_DIR / "grants.json")

    generated_ts = SRC_DATA_DIR / "grants.generated.ts"
    generated_ts.write_text(
        "/* eslint-disable */\n"
        "import type { Grant } from \"./grants\";\n\n"
        "// Auto-generated by scripts/build_grants_json.py. Do not edit manually.\n"
        f"export const GENERATED_GRANTS = {ts_string(grants)} satisfies Grant[];\n",
        encoding="utf-8",
    )

    print(f"✓ {len(grants)} Förderprogramme → public/grants.json")
    if DOCS_DIR.exists():
        print("✓ docs/grants.json synchronisiert")
    print("✓ src/data/grants.generated.ts aktualisiert")
    print(f"  Stats: {stats}")


if __name__ == "__main__":
    run()
