"""
Baut public/docs partners.json und src/data/partners.generated.ts.
"""
import json
import shutil
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
PARTNERS_DIR = ROOT / "data" / "partners"
PUBLIC_DIR = ROOT / "public"
DOCS_DIR = ROOT / "docs"
SRC_DATA_DIR = ROOT / "src" / "data"


def run() -> None:
    files = sorted(PARTNERS_DIR.glob("partners_*.json"))
    if not files:
        raise SystemExit("Keine partners_*.json gefunden. normalize_partners.py zuerst ausführen.")
    latest = files[-1]
    partners = json.loads(latest.read_text(encoding="utf-8")).get("partners", [])
    by_service = {}
    for partner in partners:
        service = partner.get("service", "mentor")
        by_service[service] = by_service.get(service, 0) + 1
    output = {
        "generated_at": datetime.now(UTC).isoformat(),
        "source_file": latest.name,
        "stats": {
            "total_partners": len(partners),
            "by_service": by_service,
            "last_updated": datetime.now(UTC).strftime("%Y-%m-%d"),
        },
        "partners": partners,
    }
    out_path = PUBLIC_DIR / "partners.json"
    out_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    if DOCS_DIR.exists():
        shutil.copyfile(out_path, DOCS_DIR / "partners.json")
    (SRC_DATA_DIR / "partners.generated.ts").write_text(
        "/* eslint-disable */\n"
        "import type { Partner } from \"./partners\";\n\n"
        "// Auto-generated by scripts/build_partners_json.py. Do not edit manually.\n"
        f"export const GENERATED_PARTNERS = {json.dumps(partners, ensure_ascii=False, indent=2)} satisfies Partner[];\n",
        encoding="utf-8",
    )
    print(f"✓ {len(partners)} Partner → public/partners.json")
    if DOCS_DIR.exists():
        print("✓ docs/partners.json synchronisiert")
    print("✓ src/data/partners.generated.ts aktualisiert")
    print(f"  Stats: {output['stats']}")


if __name__ == "__main__":
    run()
