/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SteuerRouteImport } from './routes/steuer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorenRouteImport } from './routes/mentoren'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as KapitalRouteImport } from './routes/kapital'
import { Route as HeuteRouteImport } from './routes/heute'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as EntdeckenRouteImport } from './routes/entdecken'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CoPilotRouteImport } from './routes/co-pilot'
import { Route as CoFounderRouteImport } from './routes/co-founder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as SteuerIndexRouteImport } from './routes/steuer.index'
import { Route as RechtIndexRouteImport } from './routes/recht.index'
import { Route as MentorenIndexRouteImport } from './routes/mentoren.index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as KapitalIndexRouteImport } from './routes/kapital.index'
import { Route as GrowthIndexRouteImport } from './routes/growth.index'
import { Route as FoerderungIndexRouteImport } from './routes/foerderung.index'
import { Route as TalentSlugRouteImport } from './routes/talent.$slug'
import { Route as SteuerSlugRouteImport } from './routes/steuer.$slug'
import { Route as RechtSlugRouteImport } from './routes/recht.$slug'
import { Route as MentorenSlugRouteImport } from './routes/mentoren.$slug'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as KapitalSlugRouteImport } from './routes/kapital.$slug'
import { Route as GrowthSlugRouteImport } from './routes/growth.$slug'
import { Route as FoerderungSlugRouteImport } from './routes/foerderung.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSttRouteImport } from './routes/api/stt'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SteuerRoute = SteuerRouteImport.update({
  id: '/steuer',
  path: '/steuer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenRoute = MentorenRouteImport.update({
  id: '/mentoren',
  path: '/mentoren',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalRoute = KapitalRouteImport.update({
  id: '/kapital',
  path: '/kapital',
  getParentRoute: () => rootRouteImport,
} as any)
const HeuteRoute = HeuteRouteImport.update({
  id: '/heute',
  path: '/heute',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const EntdeckenRoute = EntdeckenRouteImport.update({
  id: '/entdecken',
  path: '/entdecken',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CoPilotRoute = CoPilotRouteImport.update({
  id: '/co-pilot',
  path: '/co-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CoFounderRoute = CoFounderRouteImport.update({
  id: '/co-founder',
  path: '/co-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRoute,
} as any)
const SteuerIndexRoute = SteuerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SteuerRoute,
} as any)
const RechtIndexRoute = RechtIndexRouteImport.update({
  id: '/recht/',
  path: '/recht/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenIndexRoute = MentorenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorenRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalIndexRoute = KapitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KapitalRoute,
} as any)
const GrowthIndexRoute = GrowthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrowthRoute,
} as any)
const FoerderungIndexRoute = FoerderungIndexRouteImport.update({
  id: '/foerderung/',
  path: '/foerderung/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSlugRoute = TalentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TalentRoute,
} as any)
const SteuerSlugRoute = SteuerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SteuerRoute,
} as any)
const RechtSlugRoute = RechtSlugRouteImport.update({
  id: '/recht/$slug',
  path: '/recht/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenSlugRoute = MentorenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MentorenRoute,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalSlugRoute = KapitalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KapitalRoute,
} as any)
const GrowthSlugRoute = GrowthSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GrowthRoute,
} as any)
const FoerderungSlugRoute = FoerderungSlugRouteImport.update({
  id: '/foerderung/$slug',
  path: '/foerderung/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/growth': typeof GrowthRouteWithChildren
  '/heute': typeof HeuteRoute
  '/kapital': typeof KapitalRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mentoren': typeof MentorenRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/steuer': typeof SteuerRouteWithChildren
  '/talent': typeof TalentRouteWithChildren
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/foerderung/': typeof FoerderungIndexRoute
  '/growth/': typeof GrowthIndexRoute
  '/kapital/': typeof KapitalIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/mentoren/': typeof MentorenIndexRoute
  '/recht/': typeof RechtIndexRoute
  '/steuer/': typeof SteuerIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/heute': typeof HeuteRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/foerderung': typeof FoerderungIndexRoute
  '/growth': typeof GrowthIndexRoute
  '/kapital': typeof KapitalIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/mentoren': typeof MentorenIndexRoute
  '/recht': typeof RechtIndexRoute
  '/steuer': typeof SteuerIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/growth': typeof GrowthRouteWithChildren
  '/heute': typeof HeuteRoute
  '/kapital': typeof KapitalRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mentoren': typeof MentorenRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/steuer': typeof SteuerRouteWithChildren
  '/talent': typeof TalentRouteWithChildren
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/foerderung/': typeof FoerderungIndexRoute
  '/growth/': typeof GrowthIndexRoute
  '/kapital/': typeof KapitalIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/mentoren/': typeof MentorenIndexRoute
  '/recht/': typeof RechtIndexRoute
  '/steuer/': typeof SteuerIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/discover'
    | '/entdecken'
    | '/growth'
    | '/heute'
    | '/kapital'
    | '/marketplace'
    | '/mentoren'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/steuer'
    | '/talent'
    | '/api/stt'
    | '/auth/callback'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/foerderung/'
    | '/growth/'
    | '/kapital/'
    | '/matches/'
    | '/mentoren/'
    | '/recht/'
    | '/steuer/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/discover'
    | '/entdecken'
    | '/heute'
    | '/marketplace'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/api/stt'
    | '/auth/callback'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/foerderung'
    | '/growth'
    | '/kapital'
    | '/matches'
    | '/mentoren'
    | '/recht'
    | '/steuer'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/discover'
    | '/entdecken'
    | '/growth'
    | '/heute'
    | '/kapital'
    | '/marketplace'
    | '/mentoren'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/steuer'
    | '/talent'
    | '/api/stt'
    | '/auth/callback'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/foerderung/'
    | '/growth/'
    | '/kapital/'
    | '/matches/'
    | '/mentoren/'
    | '/recht/'
    | '/steuer/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CoFounderRoute: typeof CoFounderRoute
  CoPilotRoute: typeof CoPilotRoute
  DiscoverRoute: typeof DiscoverRoute
  EntdeckenRoute: typeof EntdeckenRoute
  GrowthRoute: typeof GrowthRouteWithChildren
  HeuteRoute: typeof HeuteRoute
  KapitalRoute: typeof KapitalRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  MentorenRoute: typeof MentorenRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SteuerRoute: typeof SteuerRouteWithChildren
  TalentRoute: typeof TalentRouteWithChildren
  ApiSttRoute: typeof ApiSttRoute
  FoerderungSlugRoute: typeof FoerderungSlugRoute
  MatchesIdRoute: typeof MatchesIdRoute
  RechtSlugRoute: typeof RechtSlugRoute
  FoerderungIndexRoute: typeof FoerderungIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  RechtIndexRoute: typeof RechtIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steuer': {
      id: '/steuer'
      path: '/steuer'
      fullPath: '/steuer'
      preLoaderRoute: typeof SteuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren': {
      id: '/mentoren'
      path: '/mentoren'
      fullPath: '/mentoren'
      preLoaderRoute: typeof MentorenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital': {
      id: '/kapital'
      path: '/kapital'
      fullPath: '/kapital'
      preLoaderRoute: typeof KapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heute': {
      id: '/heute'
      path: '/heute'
      fullPath: '/heute'
      preLoaderRoute: typeof HeuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entdecken': {
      id: '/entdecken'
      path: '/entdecken'
      fullPath: '/entdecken'
      preLoaderRoute: typeof EntdeckenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-pilot': {
      id: '/co-pilot'
      path: '/co-pilot'
      fullPath: '/co-pilot'
      preLoaderRoute: typeof CoPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-founder': {
      id: '/co-founder'
      path: '/co-founder'
      fullPath: '/co-founder'
      preLoaderRoute: typeof CoFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRoute
    }
    '/steuer/': {
      id: '/steuer/'
      path: '/'
      fullPath: '/steuer/'
      preLoaderRoute: typeof SteuerIndexRouteImport
      parentRoute: typeof SteuerRoute
    }
    '/recht/': {
      id: '/recht/'
      path: '/recht'
      fullPath: '/recht/'
      preLoaderRoute: typeof RechtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren/': {
      id: '/mentoren/'
      path: '/'
      fullPath: '/mentoren/'
      preLoaderRoute: typeof MentorenIndexRouteImport
      parentRoute: typeof MentorenRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital/': {
      id: '/kapital/'
      path: '/'
      fullPath: '/kapital/'
      preLoaderRoute: typeof KapitalIndexRouteImport
      parentRoute: typeof KapitalRoute
    }
    '/growth/': {
      id: '/growth/'
      path: '/'
      fullPath: '/growth/'
      preLoaderRoute: typeof GrowthIndexRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/foerderung/': {
      id: '/foerderung/'
      path: '/foerderung'
      fullPath: '/foerderung/'
      preLoaderRoute: typeof FoerderungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$slug': {
      id: '/talent/$slug'
      path: '/$slug'
      fullPath: '/talent/$slug'
      preLoaderRoute: typeof TalentSlugRouteImport
      parentRoute: typeof TalentRoute
    }
    '/steuer/$slug': {
      id: '/steuer/$slug'
      path: '/$slug'
      fullPath: '/steuer/$slug'
      preLoaderRoute: typeof SteuerSlugRouteImport
      parentRoute: typeof SteuerRoute
    }
    '/recht/$slug': {
      id: '/recht/$slug'
      path: '/recht/$slug'
      fullPath: '/recht/$slug'
      preLoaderRoute: typeof RechtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren/$slug': {
      id: '/mentoren/$slug'
      path: '/$slug'
      fullPath: '/mentoren/$slug'
      preLoaderRoute: typeof MentorenSlugRouteImport
      parentRoute: typeof MentorenRoute
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital/$slug': {
      id: '/kapital/$slug'
      path: '/$slug'
      fullPath: '/kapital/$slug'
      preLoaderRoute: typeof KapitalSlugRouteImport
      parentRoute: typeof KapitalRoute
    }
    '/growth/$slug': {
      id: '/growth/$slug'
      path: '/$slug'
      fullPath: '/growth/$slug'
      preLoaderRoute: typeof GrowthSlugRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/foerderung/$slug': {
      id: '/foerderung/$slug'
      path: '/foerderung/$slug'
      fullPath: '/foerderung/$slug'
      preLoaderRoute: typeof FoerderungSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GrowthRouteChildren {
  GrowthSlugRoute: typeof GrowthSlugRoute
  GrowthIndexRoute: typeof GrowthIndexRoute
}

const GrowthRouteChildren: GrowthRouteChildren = {
  GrowthSlugRoute: GrowthSlugRoute,
  GrowthIndexRoute: GrowthIndexRoute,
}

const GrowthRouteWithChildren =
  GrowthRoute._addFileChildren(GrowthRouteChildren)

interface KapitalRouteChildren {
  KapitalSlugRoute: typeof KapitalSlugRoute
  KapitalIndexRoute: typeof KapitalIndexRoute
}

const KapitalRouteChildren: KapitalRouteChildren = {
  KapitalSlugRoute: KapitalSlugRoute,
  KapitalIndexRoute: KapitalIndexRoute,
}

const KapitalRouteWithChildren =
  KapitalRoute._addFileChildren(KapitalRouteChildren)

interface MentorenRouteChildren {
  MentorenSlugRoute: typeof MentorenSlugRoute
  MentorenIndexRoute: typeof MentorenIndexRoute
}

const MentorenRouteChildren: MentorenRouteChildren = {
  MentorenSlugRoute: MentorenSlugRoute,
  MentorenIndexRoute: MentorenIndexRoute,
}

const MentorenRouteWithChildren = MentorenRoute._addFileChildren(
  MentorenRouteChildren,
)

interface SteuerRouteChildren {
  SteuerSlugRoute: typeof SteuerSlugRoute
  SteuerIndexRoute: typeof SteuerIndexRoute
}

const SteuerRouteChildren: SteuerRouteChildren = {
  SteuerSlugRoute: SteuerSlugRoute,
  SteuerIndexRoute: SteuerIndexRoute,
}

const SteuerRouteWithChildren =
  SteuerRoute._addFileChildren(SteuerRouteChildren)

interface TalentRouteChildren {
  TalentSlugRoute: typeof TalentSlugRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentSlugRoute: TalentSlugRoute,
  TalentIndexRoute: TalentIndexRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CoFounderRoute: CoFounderRoute,
  CoPilotRoute: CoPilotRoute,
  DiscoverRoute: DiscoverRoute,
  EntdeckenRoute: EntdeckenRoute,
  GrowthRoute: GrowthRouteWithChildren,
  HeuteRoute: HeuteRoute,
  KapitalRoute: KapitalRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  MentorenRoute: MentorenRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SteuerRoute: SteuerRouteWithChildren,
  TalentRoute: TalentRouteWithChildren,
  ApiSttRoute: ApiSttRoute,
  FoerderungSlugRoute: FoerderungSlugRoute,
  MatchesIdRoute: MatchesIdRoute,
  RechtSlugRoute: RechtSlugRoute,
  FoerderungIndexRoute: FoerderungIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  RechtIndexRoute: RechtIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
