/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnterlagenRouteImport } from './routes/unterlagen'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SteuerRouteImport } from './routes/steuer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorenRouteImport } from './routes/mentoren'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as KapitalRouteImport } from './routes/kapital'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as HeuteRouteImport } from './routes/heute'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as FirmaRouteImport } from './routes/firma'
import { Route as EntdeckenRouteImport } from './routes/entdecken'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CoPilotRouteImport } from './routes/co-pilot'
import { Route as CoFounderRouteImport } from './routes/co-founder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AufgabenRouteImport } from './routes/aufgaben'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as SteuerIndexRouteImport } from './routes/steuer.index'
import { Route as RechtIndexRouteImport } from './routes/recht.index'
import { Route as MentorenIndexRouteImport } from './routes/mentoren.index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as KapitalIndexRouteImport } from './routes/kapital.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GrowthIndexRouteImport } from './routes/growth.index'
import { Route as FoerderungIndexRouteImport } from './routes/foerderung.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TalentSlugRouteImport } from './routes/talent.$slug'
import { Route as SteuerSlugRouteImport } from './routes/steuer.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as RechtSlugRouteImport } from './routes/recht.$slug'
import { Route as MentorenSlugRouteImport } from './routes/mentoren.$slug'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as KapitalSlugRouteImport } from './routes/kapital.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GrowthSlugRouteImport } from './routes/growth.$slug'
import { Route as FoerderungSlugRouteImport } from './routes/foerderung.$slug'
import { Route as AuthWaitlistConfirmRouteImport } from './routes/auth.waitlist-confirm'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AdminPartnerRouteImport } from './routes/admin.partner'
import { Route as AdminGuidesRouteImport } from './routes/admin.guides'
import { Route as AdminEventsRouteImport } from './routes/admin.events'

const UnterlagenRoute = UnterlagenRouteImport.update({
  id: '/unterlagen',
  path: '/unterlagen',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SteuerRoute = SteuerRouteImport.update({
  id: '/steuer',
  path: '/steuer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenRoute = MentorenRouteImport.update({
  id: '/mentoren',
  path: '/mentoren',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalRoute = KapitalRouteImport.update({
  id: '/kapital',
  path: '/kapital',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const HeuteRoute = HeuteRouteImport.update({
  id: '/heute',
  path: '/heute',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmaRoute = FirmaRouteImport.update({
  id: '/firma',
  path: '/firma',
  getParentRoute: () => rootRouteImport,
} as any)
const EntdeckenRoute = EntdeckenRouteImport.update({
  id: '/entdecken',
  path: '/entdecken',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CoPilotRoute = CoPilotRouteImport.update({
  id: '/co-pilot',
  path: '/co-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CoFounderRoute = CoFounderRouteImport.update({
  id: '/co-founder',
  path: '/co-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AufgabenRoute = AufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRoute,
} as any)
const SteuerIndexRoute = SteuerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SteuerRoute,
} as any)
const RechtIndexRoute = RechtIndexRouteImport.update({
  id: '/recht/',
  path: '/recht/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenIndexRoute = MentorenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorenRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalIndexRoute = KapitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KapitalRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthIndexRoute = GrowthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrowthRoute,
} as any)
const FoerderungIndexRoute = FoerderungIndexRouteImport.update({
  id: '/foerderung/',
  path: '/foerderung/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TalentSlugRoute = TalentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TalentRoute,
} as any)
const SteuerSlugRoute = SteuerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SteuerRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtSlugRoute = RechtSlugRouteImport.update({
  id: '/recht/$slug',
  path: '/recht/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorenSlugRoute = MentorenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MentorenRoute,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KapitalSlugRoute = KapitalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KapitalRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthSlugRoute = GrowthSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GrowthRoute,
} as any)
const FoerderungSlugRoute = FoerderungSlugRouteImport.update({
  id: '/foerderung/$slug',
  path: '/foerderung/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWaitlistConfirmRoute = AuthWaitlistConfirmRouteImport.update({
  id: '/waitlist-confirm',
  path: '/waitlist-confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnerRoute = AdminPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aufgaben': typeof AufgabenRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/deals': typeof DealsRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/firma': typeof FirmaRoute
  '/growth': typeof GrowthRouteWithChildren
  '/heute': typeof HeuteRoute
  '/kalender': typeof KalenderRoute
  '/kanban': typeof KanbanRoute
  '/kapital': typeof KapitalRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mentoren': typeof MentorenRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/steuer': typeof SteuerRouteWithChildren
  '/talent': typeof TalentRouteWithChildren
  '/team': typeof TeamRoute
  '/unterlagen': typeof UnterlagenRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/waitlist-confirm': typeof AuthWaitlistConfirmRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/foerderung/': typeof FoerderungIndexRoute
  '/growth/': typeof GrowthIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/kapital/': typeof KapitalIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/mentoren/': typeof MentorenIndexRoute
  '/recht/': typeof RechtIndexRoute
  '/steuer/': typeof SteuerIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/deals': typeof DealsRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/firma': typeof FirmaRoute
  '/heute': typeof HeuteRoute
  '/kalender': typeof KalenderRoute
  '/kanban': typeof KanbanRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/team': typeof TeamRoute
  '/unterlagen': typeof UnterlagenRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/waitlist-confirm': typeof AuthWaitlistConfirmRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/admin': typeof AdminIndexRoute
  '/foerderung': typeof FoerderungIndexRoute
  '/growth': typeof GrowthIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/kapital': typeof KapitalIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/mentoren': typeof MentorenIndexRoute
  '/recht': typeof RechtIndexRoute
  '/steuer': typeof SteuerIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aufgaben': typeof AufgabenRoute
  '/auth': typeof AuthRouteWithChildren
  '/co-founder': typeof CoFounderRoute
  '/co-pilot': typeof CoPilotRoute
  '/deals': typeof DealsRoute
  '/discover': typeof DiscoverRoute
  '/entdecken': typeof EntdeckenRoute
  '/firma': typeof FirmaRoute
  '/growth': typeof GrowthRouteWithChildren
  '/heute': typeof HeuteRoute
  '/kalender': typeof KalenderRoute
  '/kanban': typeof KanbanRoute
  '/kapital': typeof KapitalRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mentoren': typeof MentorenRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/steuer': typeof SteuerRouteWithChildren
  '/talent': typeof TalentRouteWithChildren
  '/team': typeof TeamRoute
  '/unterlagen': typeof UnterlagenRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/api/stt': typeof ApiSttRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/waitlist-confirm': typeof AuthWaitlistConfirmRoute
  '/foerderung/$slug': typeof FoerderungSlugRoute
  '/growth/$slug': typeof GrowthSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kapital/$slug': typeof KapitalSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/mentoren/$slug': typeof MentorenSlugRoute
  '/recht/$slug': typeof RechtSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/steuer/$slug': typeof SteuerSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/foerderung/': typeof FoerderungIndexRoute
  '/growth/': typeof GrowthIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/kapital/': typeof KapitalIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/mentoren/': typeof MentorenIndexRoute
  '/recht/': typeof RechtIndexRoute
  '/steuer/': typeof SteuerIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aufgaben'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/deals'
    | '/discover'
    | '/entdecken'
    | '/firma'
    | '/growth'
    | '/heute'
    | '/kalender'
    | '/kanban'
    | '/kapital'
    | '/marketplace'
    | '/mentoren'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/steuer'
    | '/talent'
    | '/team'
    | '/unterlagen'
    | '/admin/events'
    | '/admin/guides'
    | '/admin/partner'
    | '/api/stt'
    | '/auth/callback'
    | '/auth/update-password'
    | '/auth/waitlist-confirm'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/guides/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/s/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/admin/'
    | '/foerderung/'
    | '/growth/'
    | '/guides/'
    | '/kapital/'
    | '/matches/'
    | '/mentoren/'
    | '/recht/'
    | '/steuer/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aufgaben'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/deals'
    | '/discover'
    | '/entdecken'
    | '/firma'
    | '/heute'
    | '/kalender'
    | '/kanban'
    | '/marketplace'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/team'
    | '/unterlagen'
    | '/admin/events'
    | '/admin/guides'
    | '/admin/partner'
    | '/api/stt'
    | '/auth/callback'
    | '/auth/update-password'
    | '/auth/waitlist-confirm'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/guides/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/s/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/admin'
    | '/foerderung'
    | '/growth'
    | '/guides'
    | '/kapital'
    | '/matches'
    | '/mentoren'
    | '/recht'
    | '/steuer'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aufgaben'
    | '/auth'
    | '/co-founder'
    | '/co-pilot'
    | '/deals'
    | '/discover'
    | '/entdecken'
    | '/firma'
    | '/growth'
    | '/heute'
    | '/kalender'
    | '/kanban'
    | '/kapital'
    | '/marketplace'
    | '/mentoren'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/steuer'
    | '/talent'
    | '/team'
    | '/unterlagen'
    | '/admin/events'
    | '/admin/guides'
    | '/admin/partner'
    | '/api/stt'
    | '/auth/callback'
    | '/auth/update-password'
    | '/auth/waitlist-confirm'
    | '/foerderung/$slug'
    | '/growth/$slug'
    | '/guides/$slug'
    | '/kapital/$slug'
    | '/matches/$id'
    | '/mentoren/$slug'
    | '/recht/$slug'
    | '/s/$slug'
    | '/steuer/$slug'
    | '/talent/$slug'
    | '/admin/'
    | '/foerderung/'
    | '/growth/'
    | '/guides/'
    | '/kapital/'
    | '/matches/'
    | '/mentoren/'
    | '/recht/'
    | '/steuer/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AufgabenRoute: typeof AufgabenRoute
  AuthRoute: typeof AuthRouteWithChildren
  CoFounderRoute: typeof CoFounderRoute
  CoPilotRoute: typeof CoPilotRoute
  DealsRoute: typeof DealsRoute
  DiscoverRoute: typeof DiscoverRoute
  EntdeckenRoute: typeof EntdeckenRoute
  FirmaRoute: typeof FirmaRoute
  GrowthRoute: typeof GrowthRouteWithChildren
  HeuteRoute: typeof HeuteRoute
  KalenderRoute: typeof KalenderRoute
  KanbanRoute: typeof KanbanRoute
  KapitalRoute: typeof KapitalRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  MentorenRoute: typeof MentorenRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SteuerRoute: typeof SteuerRouteWithChildren
  TalentRoute: typeof TalentRouteWithChildren
  TeamRoute: typeof TeamRoute
  UnterlagenRoute: typeof UnterlagenRoute
  ApiSttRoute: typeof ApiSttRoute
  FoerderungSlugRoute: typeof FoerderungSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  MatchesIdRoute: typeof MatchesIdRoute
  RechtSlugRoute: typeof RechtSlugRoute
  SSlugRoute: typeof SSlugRoute
  FoerderungIndexRoute: typeof FoerderungIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  RechtIndexRoute: typeof RechtIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unterlagen': {
      id: '/unterlagen'
      path: '/unterlagen'
      fullPath: '/unterlagen'
      preLoaderRoute: typeof UnterlagenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steuer': {
      id: '/steuer'
      path: '/steuer'
      fullPath: '/steuer'
      preLoaderRoute: typeof SteuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren': {
      id: '/mentoren'
      path: '/mentoren'
      fullPath: '/mentoren'
      preLoaderRoute: typeof MentorenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital': {
      id: '/kapital'
      path: '/kapital'
      fullPath: '/kapital'
      preLoaderRoute: typeof KapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heute': {
      id: '/heute'
      path: '/heute'
      fullPath: '/heute'
      preLoaderRoute: typeof HeuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firma': {
      id: '/firma'
      path: '/firma'
      fullPath: '/firma'
      preLoaderRoute: typeof FirmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entdecken': {
      id: '/entdecken'
      path: '/entdecken'
      fullPath: '/entdecken'
      preLoaderRoute: typeof EntdeckenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-pilot': {
      id: '/co-pilot'
      path: '/co-pilot'
      fullPath: '/co-pilot'
      preLoaderRoute: typeof CoPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-founder': {
      id: '/co-founder'
      path: '/co-founder'
      fullPath: '/co-founder'
      preLoaderRoute: typeof CoFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufgaben': {
      id: '/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof AufgabenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRoute
    }
    '/steuer/': {
      id: '/steuer/'
      path: '/'
      fullPath: '/steuer/'
      preLoaderRoute: typeof SteuerIndexRouteImport
      parentRoute: typeof SteuerRoute
    }
    '/recht/': {
      id: '/recht/'
      path: '/recht'
      fullPath: '/recht/'
      preLoaderRoute: typeof RechtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren/': {
      id: '/mentoren/'
      path: '/'
      fullPath: '/mentoren/'
      preLoaderRoute: typeof MentorenIndexRouteImport
      parentRoute: typeof MentorenRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital/': {
      id: '/kapital/'
      path: '/'
      fullPath: '/kapital/'
      preLoaderRoute: typeof KapitalIndexRouteImport
      parentRoute: typeof KapitalRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth/': {
      id: '/growth/'
      path: '/'
      fullPath: '/growth/'
      preLoaderRoute: typeof GrowthIndexRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/foerderung/': {
      id: '/foerderung/'
      path: '/foerderung'
      fullPath: '/foerderung/'
      preLoaderRoute: typeof FoerderungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/talent/$slug': {
      id: '/talent/$slug'
      path: '/$slug'
      fullPath: '/talent/$slug'
      preLoaderRoute: typeof TalentSlugRouteImport
      parentRoute: typeof TalentRoute
    }
    '/steuer/$slug': {
      id: '/steuer/$slug'
      path: '/$slug'
      fullPath: '/steuer/$slug'
      preLoaderRoute: typeof SteuerSlugRouteImport
      parentRoute: typeof SteuerRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recht/$slug': {
      id: '/recht/$slug'
      path: '/recht/$slug'
      fullPath: '/recht/$slug'
      preLoaderRoute: typeof RechtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoren/$slug': {
      id: '/mentoren/$slug'
      path: '/$slug'
      fullPath: '/mentoren/$slug'
      preLoaderRoute: typeof MentorenSlugRouteImport
      parentRoute: typeof MentorenRoute
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapital/$slug': {
      id: '/kapital/$slug'
      path: '/$slug'
      fullPath: '/kapital/$slug'
      preLoaderRoute: typeof KapitalSlugRouteImport
      parentRoute: typeof KapitalRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth/$slug': {
      id: '/growth/$slug'
      path: '/$slug'
      fullPath: '/growth/$slug'
      preLoaderRoute: typeof GrowthSlugRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/foerderung/$slug': {
      id: '/foerderung/$slug'
      path: '/foerderung/$slug'
      fullPath: '/foerderung/$slug'
      preLoaderRoute: typeof FoerderungSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/waitlist-confirm': {
      id: '/auth/waitlist-confirm'
      path: '/waitlist-confirm'
      fullPath: '/auth/waitlist-confirm'
      preLoaderRoute: typeof AuthWaitlistConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partner': {
      id: '/admin/partner'
      path: '/partner'
      fullPath: '/admin/partner'
      preLoaderRoute: typeof AdminPartnerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminPartnerRoute: typeof AdminPartnerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminPartnerRoute: AdminPartnerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthWaitlistConfirmRoute: typeof AuthWaitlistConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthWaitlistConfirmRoute: AuthWaitlistConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GrowthRouteChildren {
  GrowthSlugRoute: typeof GrowthSlugRoute
  GrowthIndexRoute: typeof GrowthIndexRoute
}

const GrowthRouteChildren: GrowthRouteChildren = {
  GrowthSlugRoute: GrowthSlugRoute,
  GrowthIndexRoute: GrowthIndexRoute,
}

const GrowthRouteWithChildren =
  GrowthRoute._addFileChildren(GrowthRouteChildren)

interface KapitalRouteChildren {
  KapitalSlugRoute: typeof KapitalSlugRoute
  KapitalIndexRoute: typeof KapitalIndexRoute
}

const KapitalRouteChildren: KapitalRouteChildren = {
  KapitalSlugRoute: KapitalSlugRoute,
  KapitalIndexRoute: KapitalIndexRoute,
}

const KapitalRouteWithChildren =
  KapitalRoute._addFileChildren(KapitalRouteChildren)

interface MentorenRouteChildren {
  MentorenSlugRoute: typeof MentorenSlugRoute
  MentorenIndexRoute: typeof MentorenIndexRoute
}

const MentorenRouteChildren: MentorenRouteChildren = {
  MentorenSlugRoute: MentorenSlugRoute,
  MentorenIndexRoute: MentorenIndexRoute,
}

const MentorenRouteWithChildren = MentorenRoute._addFileChildren(
  MentorenRouteChildren,
)

interface SteuerRouteChildren {
  SteuerSlugRoute: typeof SteuerSlugRoute
  SteuerIndexRoute: typeof SteuerIndexRoute
}

const SteuerRouteChildren: SteuerRouteChildren = {
  SteuerSlugRoute: SteuerSlugRoute,
  SteuerIndexRoute: SteuerIndexRoute,
}

const SteuerRouteWithChildren =
  SteuerRoute._addFileChildren(SteuerRouteChildren)

interface TalentRouteChildren {
  TalentSlugRoute: typeof TalentSlugRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentSlugRoute: TalentSlugRoute,
  TalentIndexRoute: TalentIndexRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AufgabenRoute: AufgabenRoute,
  AuthRoute: AuthRouteWithChildren,
  CoFounderRoute: CoFounderRoute,
  CoPilotRoute: CoPilotRoute,
  DealsRoute: DealsRoute,
  DiscoverRoute: DiscoverRoute,
  EntdeckenRoute: EntdeckenRoute,
  FirmaRoute: FirmaRoute,
  GrowthRoute: GrowthRouteWithChildren,
  HeuteRoute: HeuteRoute,
  KalenderRoute: KalenderRoute,
  KanbanRoute: KanbanRoute,
  KapitalRoute: KapitalRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  MentorenRoute: MentorenRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SteuerRoute: SteuerRouteWithChildren,
  TalentRoute: TalentRouteWithChildren,
  TeamRoute: TeamRoute,
  UnterlagenRoute: UnterlagenRoute,
  ApiSttRoute: ApiSttRoute,
  FoerderungSlugRoute: FoerderungSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  MatchesIdRoute: MatchesIdRoute,
  RechtSlugRoute: RechtSlugRoute,
  SSlugRoute: SSlugRoute,
  FoerderungIndexRoute: FoerderungIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  RechtIndexRoute: RechtIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
