create table if not exists public.copilot_execution_agents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  agent_key text not null,
  name text not null,
  purpose text not null default '',
  status text not null default 'idle'
    check (status in ('idle', 'working', 'blocked', 'failed')),
  working_memory jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  unique (user_id, agent_key)
);

alter table public.copilot_execution_jobs
  add column if not exists agent_id uuid
    references public.copilot_execution_agents(id) on delete set null,
  add column if not exists current_step integer not null default 0,
  add column if not exists max_steps integer not null default 4,
  add column if not exists attempts integer not null default 0,
  add column if not exists failure_count integer not null default 0,
  add column if not exists next_run_at timestamptz not null default now(),
  add column if not exists last_heartbeat_at timestamptz,
  add column if not exists progress_text text,
  add column if not exists working_memory jsonb not null default '{}'::jsonb,
  add column if not exists result jsonb,
  add column if not exists result_sent_at timestamptz;

create table if not exists public.copilot_execution_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.copilot_execution_jobs(id) on delete cascade,
  agent_id uuid references public.copilot_execution_agents(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null
    check (kind in (
      'request',
      'plan',
      'tool_call',
      'tool_result',
      'progress',
      'response',
      'error',
      'status'
    )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_copilot_execution_jobs_queue
  on public.copilot_execution_jobs(status, next_run_at, created_at);
create index if not exists idx_copilot_execution_events_job
  on public.copilot_execution_events(job_id, created_at);
create index if not exists idx_copilot_execution_agents_user
  on public.copilot_execution_agents(user_id, last_used_at desc);

grant select on public.copilot_execution_agents to authenticated;
grant select on public.copilot_execution_events to authenticated;
grant all on public.copilot_execution_agents to service_role;
grant all on public.copilot_execution_events to service_role;
grant usage, select on sequence public.copilot_execution_events_id_seq to service_role;

alter table public.copilot_execution_agents enable row level security;
alter table public.copilot_execution_events enable row level security;

drop policy if exists "Users read own copilot execution agents"
  on public.copilot_execution_agents;
create policy "Users read own copilot execution agents"
  on public.copilot_execution_agents
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users read own copilot execution events"
  on public.copilot_execution_events;
create policy "Users read own copilot execution events"
  on public.copilot_execution_events
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.claim_copilot_execution_job(
  requested_job_id uuid default null
)
returns setof public.copilot_execution_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidate as (
    select job.id
    from public.copilot_execution_jobs job
    where (
      (
          job.status = 'queued'
          and job.next_run_at <= now()
        )
        or (
          job.status = 'running'
          and coalesce(job.last_heartbeat_at, job.started_at, job.updated_at)
            < now() - interval '2 minutes'
        )
      )
      and (requested_job_id is null or job.id = requested_job_id)
    order by job.created_at
    for update skip locked
    limit 1
  )
  update public.copilot_execution_jobs job
  set
    status = 'running',
    attempts = job.attempts + 1,
    started_at = coalesce(job.started_at, now()),
    last_heartbeat_at = now(),
    updated_at = now()
  from candidate
  where job.id = candidate.id
  returning job.*;
end;
$$;

revoke all on function public.claim_copilot_execution_job(uuid) from public;
grant execute on function public.claim_copilot_execution_job(uuid) to service_role;

do $$
declare
  project_url text;
  service_key text;
begin
  create extension if not exists pg_cron;
  create extension if not exists pg_net;

  begin
    perform cron.unschedule('matchfoundr-copilot-worker');
  exception when others then
    null;
  end;

  select decrypted_secret into project_url
  from vault.decrypted_secrets
  where name = 'project_url';

  select decrypted_secret into service_key
  from vault.decrypted_secrets
  where name = 'service_role_key';

  if project_url is null or service_key is null then
    raise notice 'copilot worker recovery cron not scheduled: Vault secrets missing';
    return;
  end if;

  perform cron.schedule(
    'matchfoundr-copilot-worker',
    '* * * * *',
    format(
      $job$
        select net.http_post(
          url := %L,
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || %L
          ),
          body := '{"drain":true}'::jsonb
        );
      $job$,
      rtrim(project_url, '/') || '/functions/v1/copilot-worker',
      service_key
    )
  );
exception when others then
  raise notice 'copilot worker recovery cron setup skipped: %', sqlerrm;
end $$;
