-- Founder Radar briefs generated by the native app / Edge Function.

create table if not exists public.founder_radar_briefs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  overall_score integer not null check (overall_score between 0 and 100),
  verdict text not null,
  urgency text not null,
  primary_risk text not null,
  hidden_opportunity text not null,
  investor_question text not null,
  signals jsonb not null default '[]'::jsonb,
  moves jsonb not null default '[]'::jsonb,
  source text not null default 'live' check (source in ('live', 'local')),
  created_at timestamptz not null default now()
);

alter table public.founder_radar_briefs enable row level security;

create policy "Users read own founder radar briefs"
  on public.founder_radar_briefs
  for select
  using (auth.uid() = user_id);

create policy "Users insert own founder radar briefs"
  on public.founder_radar_briefs
  for insert
  with check (auth.uid() = user_id);

create index if not exists idx_founder_radar_briefs_user_created
  on public.founder_radar_briefs(user_id, created_at desc);
