"""Write ../timing.js from the processed voice lines: word onsets plus a 100 Hz loudness envelope per line.

python timing.py <clean voice dir> <out timing.js>
"""
import json
import sys
import warnings
from pathlib import Path

import numpy as np
from scipy.io import wavfile

warnings.simplefilter('ignore', wavfile.WavFileWarning)
d = Path(sys.argv[1])
meta = json.loads((d / 'voice.json').read_text())
out = []
for l in meta['lines']:
    sr, x = wavfile.read(d / f"{l['id']}.wav")
    x = x.astype(np.float64) / 32768
    hop, win = sr // 100, int(sr * 0.03)
    pad = np.pad(x, (win // 2, win // 2))
    fr = np.lib.stride_tricks.sliding_window_view(pad, win)[::hop]
    db = 20 * np.log10(np.sqrt((fr ** 2).mean(axis=1)) + 1e-9)
    env = np.clip((db - (db.max() - 34)) / 30, 0, 1)
    out.append({**{k: l[k] for k in ('id', 'who', 'text', 'dur', 'words')}, 'env': [round(float(v), 2) for v in env]})
js = '// Generated by tools/timing.py from audio/voice/clean/voice.json. Do not edit by hand.\n'
js += 'window.VOICE = ' + json.dumps({'tempo': meta['tempo'], 'lines': out}, ensure_ascii=False, separators=(',', ':')) + ';\n'
Path(sys.argv[2]).write_text(js)
print('wrote', sys.argv[2], len(js), 'bytes')
